//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_RECORED
    {
        public System.DateTime RECORED_TIME { get; set; }
        public string CAR_TYPE { get; set; }
        public string STATION_SQ { get; set; }
        public string CHR_HYP { get; set; }
        public long INT_SEQ { get; set; }
        public int INT_KAISOU_LVL { get; set; }
        public string CHR_HYP_PARN { get; set; }
        public string CHR_HYP_PS { get; set; }
        public string CHR_NUB_HYP_LOT { get; set; }
        public decimal NUM_TORIGIKI_SU { get; set; }
        public int INT_NUB_HIKITORI_KANB { get; set; }
        public int NUM_USED { get; set; }
        public int NUM_SUR_USE_HYP_PARN { get; set; }
        public int NUM_SUR_USE_HYP_PS { get; set; }
        public string CHR_KBN_ERROR { get; set; }
        public int INT_SQ { get; set; }
    }
}
