//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plc
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Test
    {
        public System.Guid Id { get; set; }
        public string D600 { get; set; }
        public string D610 { get; set; }
        public string D620 { get; set; }
        public string D640 { get; set; }
        public string D660 { get; set; }
        public string D670 { get; set; }
        public float D816 { get; set; }
        public float D818 { get; set; }
        public float D820 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool M1007 { get; set; }
    }
}
